<?php

namespace LandingBundle\Repository;

/**
 * PotentialClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PotentialClientRepository extends \Doctrine\ORM\EntityRepository
{
}
