<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotEmptyCategories()
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.places', 'p')
            ->where('SIZE(c.places) > 0')
            ->getQuery()
            ->getResult();
    }
}
