imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    web_dir: '%kernel.root_dir%/../web'
    uploads_dir: '%kernel.root_dir%/../web/uploads'
    temp_dir: '%kernel.root_dir%/../web/uploads/tmp'
    places_dir: '%kernel.root_dir%/../web/uploads/places'
    categories_dir: '%kernel.root_dir%/../web/uploads/categories'
    events_dir: '%kernel.root_dir%/../web/uploads/events'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
#    param_fetcher_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: false
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

#fos_elastica:
#    clients:
#        default: { host: localhost, port: 9200 }
#    indexes:
#        budapp:
#            finder: ~
#            index_name: "budapp_%kernel.environment%"
#            types:
#                category:
#                    mappings:
#                        name: ~
#                    persistence:
#                        driver: orm
#                        model: AppBundle\Entity\Category
#                        provider: ~
#                        listener: ~
#                        finder: ~
#                event:
#                    mappings:
#                        title: ~
#                        descriptionBlock1: ~
#                        descriptionBlock2: ~
#                        location: ~
#                    persistence:
#                        driver: orm
#                        model: AppBundle\Entity\Event
#                        provider: ~
#                        listener: ~
#                        finder: ~
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                day: DoctrineExtensions\Query\Mysql\Day
                now: DoctrineExtensions\Query\Mysql\Now
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
