app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@ApiBundle/Controller/"
    type:     annotation

rest:
    type: rest
    resource: routing_rest.yml
    prefix: /api