# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$6JaZlOR1WFlkM0stawa5qeCrRJZ2PXV/6RdF9cBdqJ5YQ4FnqoBg2
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$YBROjEdeH92IaIqAPhUyfulXb15Fb2neDOUnbOIloSKe.N4UChI6K
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            # activate different ways to authenticate

        default:
            anonymous: ~
            http_basic: ~

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/landing, roles: ROLE_USER }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/api/secure, roles: ROLE_ADMIN }

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12